// vue3-vite-js/src/views/404.vue
<template>
	<a-result status="404" title="404" sub-title="页面不存在~">
		<template #extra>
			<a-button @click="goHome">返回</a-button>
		</template>
	</a-result>
</template>

<script setup>
import { useRouter } from 'vue-router';

const router = useRouter();

const goHome = () => {
	router.push({ path: '/' });
};
</script>

// react-vite-js/src/views/error/404.jsx
import { Button, Result } from 'antd';
import { useNavigate } from 'react-router-dom';
import { VIEW_WELCOME } from '@/constants/modules/route';

const NotFound = () => {
	const navigate = useNavigate();
	const goHome = () => {
		navigate(VIEW_WELCOME);
	};
	return (
		<Result
			status='404'
			title='404'
			subTitle='Sorry, the page you visited does not exist.'
			extra={<Button onClick={goHome}>返回</Button>}
		/>
	);
};

export default NotFound;
